### PR TITLE
Compiler options in pom.xml

### PR DESCRIPTION
**Pull request by agazzarini**
Hi @RubenVerborgh I closed the previous PR and this is the new one that contains only changes related with compiler options.

AG

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Great, thanks! Traveling now, but will look at this soon!

**Comment by agazzarini** [comment]
@RubenVerborgh still on this topic: Java7 reached its EOL in April....maybe Java8 is a better choice. What do you think?

**Comment by RubenVerborgh** [comment]
Many servers have not switched to Java 8, I'm afraid we will get complaints if we do.

**Comment by agazzarini** [comment]
Sure, I see. That's a shame, as I imagine an "intelligent" client could
benefit from things introduced in Java 8 (e.g. parallel streams) but ok,
you're right

**Pull request closed without merging**
