### PR TITLE
Java 8 - Jena 3.1

### PR DESCRIPTION
**Pull request by ghsnd**
Update to Java 8, Jena 3.1.0 (which requires Java >= 8), other libraries updated as well. Tried to change the code as little as possible. This could be a basis for further development.

Cheers,
Gerald

### CODE REVIEW

**Comment by ghsnd** [comment]
It does not need to be merged in the _master_ branch, since companies still might use Java 7...

**Comment by rubensworks** [comment]
Do the library updates require Java 8?
If not, these library updates could be merged into the `master` branch, and the Java 8 code changes to `develop`?

**Comment by ghsnd** [comment]
I think this version of log4j requires java 8. But it can be changed to a version < 2.4, which I think doesn't. As far as I can tell, the other libraries don't require Java 8.

**Comment by laurensdv** [comment]
Java 8 is the default version now, the Java 7 version is no longer supported.

**Pull request merged**
